import os

success = False

with open("../materialicons.go", "w") as output:
    output.write("""package materialicons

// generated by util/gen_icon_symbols.py

type Icon rune

const (
""")
    for line in open("./codepoints").readlines():
        name, codepoint = line.split(" ")
        output.write("Icon%s Icon = 0x%s" % (name.title().replace("_", ""), codepoint))
    output.write(")") 
    success = True

if success:
    os.system("go fmt ../materialicons.go")

