import os
import time

success = False

with open("../entypoicons.go", "w") as output:
    output.write("""package nanogui

// generated by util/gen_icon_symbols.py

type Icon rune

const (
""")
    name = ""
    for line in open("./entypo.yml").readlines():
        if line.startswith("  - css: "):
            name = line.split(":")[1].strip()
        elif line.startswith("    code: "):
            codepoint = line.split(":")[1].strip()
            output.write("Icon%s Icon = %s\n" % (name.title().replace("-", ""), codepoint))
    output.write(")") 
    success = True

if success:
    os.system("go fmt ../entypoicons.go") 
