with open("../materialicons.go", "w") as output:
    output.write("""package nanogui

// generated by util/gen_icon_symbols.py

type Icon rune

const (
""")
    for line in open("./codepoints").readlines():
        name, codepoint = line.split(" ")
        output.write("    Icon%s Icon = 0x%s" % (name.title().replace("_", ""), codepoint))
    output.write(")") 

